- .github/workflows/ci-cd-workflow.yml
- mesmer/calibrate_mesmer/calibrate_mesmer.py
Note that this should fail now, isort is not yet run.
> add isort to CI

- doc/source/api.rst
- doc/source/conf.py
- doc/source/index.rst
Here's my contribution to #46.
- Writing a high-level description of MESMER. But I struggled a bit with what to include. Is it about what you envisioned @mathause? If not, feel free to change it! 
- Merging the most up-to-date master into the `add_initial_docs` branch and subsequently removing a no longer implemented function form the autosummary. 
- Changing Zeb to Zebedee to be consistent with @znicholls name throughout the repo. 
We should merge this (or an updated version of it after your review) into #46 before we merge #46 into master.
> Add initial docs contributions from @leabeusch

- CHANGELOG.rst
Just a small PR so we have a commit that says v0.8.1
> Release v0.8.1

- CHANGELOG.rst
- docs/source/index.rst
- mesmer/calibrate_mesmer/train_gv.py
- mesmer/calibrate_mesmer/train_lv.py
- mesmer/create_emulations/create_emus_gv.py
Small changes to the docs:
- update `CHANGELOG.rst`
- add 0.9.0
- add subsections
- slight reordering of `index.rst`
- some small fixes to docstrings
@znicholls I changed the proposed sections from `Keep a Changelog` and used the ones from xarray - let's see how that works. I am going to merge now because I want to add an entry in another PR. If you disagree we can update in a follow up PR.
> small doc updates

- .github/workflows/ci-cd-workflow.yml
- CHANGELOG.rst
- Makefile
- docs/source/conf.py
Fixes the copyright and release version in the docs
> Fix copyright in docs

- docs/source/api.rst
Follow up of #55 - fixes the API docs.
> fix docs of load_cmipng (#55 follow up)

- CHANGELOG.rst
A small PR to have a commit that says v0.8.3.
> Release v0.8.3

- AUTHORS
@woodhome23 I added to the AUTHOR file. Do you want a description?
B.t.w. you can give yourself a _Name_ in https://github.com/settings/profile
> add Jonas in AUTHORS

- .github/workflows/ci-cd-workflow.yml
- CHANGELOG.rst
- setup.py
> support python 3.10

- README.rst
Update the reference now that the paper is out.
> Update GMD paper in README.rst

- CHANGELOG.rst
- docs/source/api.rst
- mesmer/core/computation.py
- mesmer/io/load_constant_files.py
- tests/test_phi_gc.py
> move gaspari_cohn and calc_geodist_exact to core

- pyproject.toml
@snath-xoc I am excluding your MESMER_M notebook from being reformated with black. I am not sure what your state is here but I don't want to mess this up for you. (However, we should eventually reformat your code but that can wait.)
> black: ignore MESMER_M notebook

- docs/source/conf.py
> docs/source/conf.py: isort

- CHANGELOG.rst
- docs/source/api.rst
> fix typos smoothing

- .github/workflows/ci-cd-workflow.yml
- docs/source/development.rst
I did not rename master to main in the docu and workflows. This PR fixes that.
> rename master branch to main

- mesmer/io/save_mesmer_bundle.py
Follow up to #197 - fixes `filename.pkl.pkl`.
> save_mesmer_data: fix filename

- docs/source/api.rst
Fixes some sphinx warnings I encountered...
> docs: fix sphinx warnings

- CHANGELOG.rst
> CHANGELOG: fix indentation

- setup.cfg
flake8 no longer accepts inline comments in the config file...
> fix config for flake8 6.0

- .github/workflows/ci-cd-workflow.yml
- Makefile
- environment.yml
Use micromamba instead of miniconda to create the test environment. That should cut down the time needed to setup the test environment considerably...
> github actions: use micromamba

- mesmer/testing.py
- tests/integration/test_calibrate_mesmer.py
- tests/integration/test_load_cmipng.py
- tests/unit/test_testing.py
Renames `_check_dict` to `assert_dict_allclose` and adds tests.
> add tests for assert_dict_allclose

- configs/config_across_scen_T_cmip6ng_test.py
- docs/source/api.rst
- mesmer/calibrate_mesmer/calibrate_mesmer.py
- mesmer/create_emulations/__init__.py
- mesmer/create_emulations/make_realisations.py
- tests/unit/test_seed_dict.py
Refactor the seed creation into a function. Remove unneeded seeds in _calibrate_mesmer.py_
> refactor seed generation

- mesmer/io/save_mesmer_bundle.py
> makedirs: use exist_ok=True

- tests/unit/test_grid.py
- tests/unit/test_regionmaskcompat.py
Remove some unnecessary prints.
> tests: remove stray prints

- CHANGELOG.rst
- mesmer/create_emulations/create_emus_lt.py
- mesmer/create_emulations/create_emus_lv.py
- mesmer/create_emulations/utils.py
> use LinearRegression.predict()

- tests/unit/test_testing.py
Not entirely sure how important this actually is but tested it tested...
> test testing

- mesmer/calibrate_mesmer/calibrate_mesmer.py
- mesmer/create_emulations/create_emus_lt.py
- mesmer/io/load_obs.py
- mesmer/stats/auto_regression.py
- mesmer/utils/convert.py
- tests/integration/test_calibrate_mesmer.py
- tests/integration/test_draw_realisations_from_bundle.py
- tests/unit/test_phi_gc.py
This gathers a number of code cleanups, removing some TODOs.
> code cleanups

- docs/environment.yml
- environment.yml
- setup.cfg
pin black to a version below 23.1 to avoid collapsing the opening newline
> pin pandas < 2.0 and black < 23.1

- mesmer/calibrate_mesmer/train_lv.py
- tests/integration/test_load_cmipng.py
> remove unneeded print & variables

- mesmer/calibrate_mesmer/train_gv.py
- mesmer/calibrate_mesmer/train_lv.py
- mesmer/create_emulations/create_emus_gv.py
- mesmer/create_emulations/create_emus_lt.py
- mesmer/create_emulations/create_emus_lv.py
- mesmer/create_emulations/utils.py
- mesmer/io/_load_cmipng.py
- mesmer/io/load_obs.py
> minor cleanups

- examples/train_create_emus_automated.py
- mesmer/calibrate_mesmer/calibrate_mesmer.py
- mesmer/create_emulations/create_emus_gt.py
- mesmer/create_emulations/create_emus_lt.py
- mesmer/create_emulations/utils.py
- mesmer/utils/convert.py
Another refactor that should only contain internal changes.
> refactor _calibrate_and_draw_realisations

- configs/config_across_scen_T_cmip6ng_test.py
- mesmer/io/_load_cmipng.py
- mesmer/io/load_constant_files.py
Another internal refactoring. Splits the data loading onto individual lines, and simplifies the anomaly computation.
> refactor _load_cmipng/ anomaly calc

- examples/config_across_scen_T_cmip6ng_test.py
In #261 I forgot to commit the config file
> add config file again (#261 follow up)

- mesmer/io/_load_cmipng.py
> load_cmipng: use wrap_to_360 & small refactor

- CHANGELOG.rst
- docs/source/api.rst
- mesmer/core/grid.py
- mesmer/core/regionmaskcompat.py
- mesmer/create_emulations/utils.py
- mesmer/io/load_constant_files.py
- mesmer/utils/select.py
> docs: various fixes and restructuring

- .github/workflows/ci-cd-workflow.yml
- CHANGELOG.rst
- setup.cfg
> test python 3.11

- mesmer/calibrate_mesmer/train_gt.py
- mesmer/create_emulations/create_emus_gt.py
- mesmer/io/load_constant_files.py
- mesmer/utils/select.py
Another bunch of small fixes (most of it messed up by me) and renaming `var` to `data` (as `var` sounded like variability to me...)
> small fixes and refactoring

- mesmer/stats/auto_regression.py
Well it's also one code improvement...
> auto_regression: small doc improvements

- mesmer/__init__.py
- mesmer/calibrate_mesmer/train_gt.py
- mesmer/core/_data.py
- mesmer/io/load_obs.py
- tests/unit/test_data.py
Move the function to load the aod data.
> move load_strat_aod function

- examples/train_create_emus_automated.py
@leabeusch I tried to split the example into a training and emulation part. Does this look ok?
> example: split training and emulation

- CHANGELOG.rst
- mesmer/create_emulations/create_emus_gv.py
- mesmer/create_emulations/create_emus_lv.py
- mesmer/stats/auto_regression.py
- tests/unit/test_auto_regression.py
Coe*ff*icients is written with two fs...
> rename coefs to coeffs

- CHANGELOG.rst
- mesmer/calibrate_mesmer/train_gv.py
- mesmer/calibrate_mesmer/train_lv.py
- mesmer/stats/auto_regression.py
- tests/unit/test_auto_regression.py
> fix AR_result ~co~variance (#317)

- examples/train_create_emus_automated.py
- mesmer/create_emulations/make_realisations.py
- tests/integration/test_draw_realisations_from_bundle.py
Simplifies the example a bit more by using the `make_realisations` helper function.
> example use make_realisations function

- docs/source/api.rst
- examples/train_create_emus_automated.py
- mesmer/create_emulations/create_emus_gv.py
- mesmer/create_emulations/create_emus_lt.py
> fix various small issues

- mesmer/core/utils.py
- tests/unit/test_utils.py
This is all internal so no changelog.
> changed time freq strings

- mesmer/__init__.py
> import stats to main namespace

- CHANGELOG.rst
- docs/source/api.rst
- mesmer/core/weighted.py
- mesmer/io/_load_cmipng.py
- mesmer/stats/_auto_regression.py
Some fixes to the docs and docstring, including a call to `velin mesmer`.
> docs and docstring fixes

- CHANGELOG.rst
Finally! There is still stuff missing but that is not extremely essential...
> release v0.9.0

- CHANGELOG.rst
> new changelog section

- .readthedocs.yml
- docs/environment.yml
There seems to be some bloat in the docs environment. Let's try to trim this down.
> simplify and update doc environment

- .github/workflows/pypi-release.yaml
I think this lead to a failure in the upload to pypi...
> use upload-artifact@v4

- CHANGELOG.rst
> new changelog section for v0.11.0

- README.rst
> README: fix space

- tests/integration/test_volc.py
> Fix volcanic tests

- .github/workflows/ci-cd-workflow.yml
- .gitignore
Remove linting from GitHub workflow cicd after adding pre-commit ci in #391, Closes #392 
Also added the .DS_Store file to the .gitignore
> remove linting GHA; update .gitignore

- CHANGELOG.rst
- mesmer/stats/_auto_regression.py
- tests/unit/test_auto_regression.py
Closes #319 
Tests added
Documentation added and changed std to variance in _fit_auto_regression_np returns (see also #317).
> Let fit AR return nobs

- tests/integration/test_calibrate_mesmer_newcodepath.py
> New calibration integration test

- mesmer/core/utils.py
- tests/unit/test_localized_covariance.py
- tests/unit/test_utils.py
> Add warning if first element is selected as local min

- .github/workflows/ci-workflow.yml
Directly relevant for #408 but probably generally a good idea here.
> GHA: don't fail fast

- .github/workflows/ci-workflow.yml
:grimacing: - `min-all-deps` was not actually checking the minimum versions
> fix min-all-deps check

- mesmer/mesmer_m/harmonic_model.py
renaming of variables and enhancing documentation
> harmonic model documentation

- mesmer/mesmer_m/power_transformer.py
Factor out the eps for readability.
> Factor out eps in pt transform

- CHANGELOG.rst
- ci/requirements/min-all-deps.yml
- docs/source/installation.rst
- environment.yml
- setup.cfg
This cleans up the dependencies in `setup.cfg` and `environment.yml` and explicitly lists all of our direct dependencies.
> clean up dependencies

- .readthedocs.yml
- CHANGELOG.rst
> Unshallow checkout

- .github/workflows/ci-workflow.yml
Should add color to the output on GHA
> GHA: add color output

- mesmer/mesmer_x/OLD_train_l_distrib.py
- mesmer/mesmer_x/create_emus_l_distrib.py
- mesmer/mesmer_x/temporary_config_all.py
- mesmer/mesmer_x/temporary_support.py
- mesmer/mesmer_x/train_l_distrib_mesmerx.py
Replaces ` Exception` by `ValueError` as the former is too general. These can potentially be refined as we work through the code.
> MESMER-X: replace bare Exception

- mesmer/mesmer_x/temporary_config_all.py
- mesmer/mesmer_x/temporary_support.py
- mesmer/mesmer_x/train_l_distrib_mesmerx.py
- mesmer/mesmer_x/train_utils_mesmerx.py
I extracted some changes from #466
- more reformatting
- created f-strings
- import `scipy` instead `scipy.stats`
```diff
-import scipy.stats as ss
+import scipy as sp
```
- define module-level variables, which allow to write some code more concisely
```
_DISCRETE_DISTRIBUTIONS = ...
_CONTINUOUS_DISTRIBUTIONS = ...
_ALL_DISTRIBUTIONS = ...
_NUMBERS = ...
```
---
Just for reference - here is how I did this:
<details>
```bash
git switch mesmer_x_first_code_updates
git reset --soft $(git merge-base main HEAD)
git commit -m "MESMER-X: first code updates"
git push origin HEAD --force
git co -b mx_more_trivial_updates
git cherry-pick mesmer_x_first_code_updates
git reset --soft 02169332a342275bf7e12db0dade60b5312ecc93
git restore --staged .
git add -u -p
```
</details>
> MESMER-X: more restructuring, define module-level variables

- mesmer/mesmer_m/power_transformer.py
- tests/unit/test_power_transformer.py
Remove duplication of lambda function for getting lambdas from xarray. This needed some reformulation of the lambda function.
> Reuse lambda function

- CHANGELOG.rst
- examples/example_mesmer_x.py
- mesmer/mesmer_x/OLD_train_l_distrib.py
- mesmer/mesmer_x/create_emus_l_distrib.py
- mesmer/mesmer_x/temporary_config_all.py
- mesmer/mesmer_x/train_l_distrib_mesmerx.py
- mesmer/mesmer_x/train_utils_mesmerx.py
- mesmer/stats/_auto_regression.py
- mesmer/stats/_harmonic_model.py
- mesmer/stats/_power_transformer.py
- tests/unit/test_power_transformer.py
```bash
codespell --skip=".git,devel,_build" --ignore-words-list "varn, THIRDPARTY" . --write-changes -i 3
```
> fix typos (using codespell)

- docs/source/development.rst
I revised the development guide and updated some of the information given there. I also added info on how to submit a pull request.
> Refine development guide

- CHANGELOG.rst
- docs/source/development.rst
- docs/source/installation.rst
I didn't test if the instructions to install the environment actually work, so here are the fixes
> Update conda environment creation

- mesmer/mesmer_x/train_utils_mesmerx.py
- tests/unit/test_mesmer_x_expression.py
Some first unit tests for `Expression`. Exposed #525. What I am not quite sure yet: should I also do some refactoring here?
> mesmer_x: add tests for `Expression`

- tests/unit/test_mesmer_x_expression.py
xref https://github.com/MESMER-group/mesmer/issues/525#issuecomment-2385065252
I'll probably just merge once the tests are run.
> `Expression`: more parsing tests

- docs/source/development.rst
Small fix. I'll merge right away as to point Yann to the docs.
> DOC: small update to development.rst

- .github/workflows/ci-workflow.yml
- CHANGELOG.rst
- setup.cfg
It usually takes a while until all dependencies support the a new python version, so let's try
> add python 3.13 to supported versions

- mesmer/__init__.py
- mesmer/calibrate_mesmer/calibrate_mesmer.py
- mesmer/calibrate_mesmer/train_lv.py
- mesmer/core/geospatial.py
- mesmer/create_emulations/make_realisations.py
- mesmer/io/_load_cmipng.py
- mesmer/io/load_constant_files.py
- pyproject.toml
> enforce absolute imports

- .github/workflows/upstream-dev-ci.yaml
- ci/install-upstream-wheels.sh
I cannot reproduce #575 locally - so let's output the list of installed packages. To see if there is any difference. I removed the line breaks from the `pip install ...` commands so they are easier to copy.
> mamba list for upstream CI

- CHANGELOG.rst
Adds Changelog entries for all PRs dealing with `DataTree` up until #537
> Add Changelog entries for `DataTree` changes

- mesmer/__init__.py
> ignore __version__ fallback in coverage

- .github/workflows/ci-workflow.yml
- .github/workflows/upstream-dev-ci.yaml
The workflows only need to run in the main repo.
> only run workflows in MESMER-group repo

- mesmer/core/geospatial.py
- mesmer/stats/_auto_regression.py
> fix array to scalar warnings

- CHANGELOG.rst
- mesmer/core/utils.py
- mesmer/stats/_harmonic_model.py
- tests/unit/test_harmonic_model.py
@sarasita thanks for the issue. I added some more sanity checks for the input of `fit_harmonic_model`
> fit_harmonic_model: more validity checks of input

- CHANGELOG.rst
- ci/requirements/min-all-deps.yml
- environment.yml
> install filefisher from conda

- mesmer/core/datatree.py
- tests/unit/test_datatree.py
> _datatree_wrapper: TypeError if DataTree in kwargs

- mesmer/core/geospatial.py
- mesmer/core/utils.py
- mesmer/stats/_localized_covariance.py
- tests/unit/test_utils.py
> make create_equal_dim_names private

- mesmer/core/_datatreecompat.py
- mesmer/core/datatree.py
- mesmer/mesmer_x/train_l_distrib_mesmerx.py
- mesmer/stats/_auto_regression.py
- mesmer/stats/_harmonic_model.py
- mesmer/stats/_linear_regression.py
Add on to #652:
-> Make all functions that are defined within functions private
> Additional privatization of functions

- examples/example_mesmer_m.ipynb
> mesmer-m example: clean output

- mesmer/core/_data.py
Use pooch after #665 is merged. No idea how I got the hash wrong... Ah yes I know: pre-commit-ci removed some whitespaces.
> aod data: use pooch

- docs/source/conf.py
- docs/source/development.rst
- docs/source/installation.rst
- mesmer/core/mask.py
- mesmer/core/regionmaskcompat.py
Run
```
cd docs
make linkcheck
```
and fix stuff manually... (most of them are redirects or permanent redirects) some of the paper links still fail with the linkcheck but work manually (probably the user agent is not allowed)
> sphinx linkcheck

- docs/source/api.rst
- mesmer/core/example_data.py
> cmip6_ng_path: add docstring

- tests/legacy/test_calibrate_mesmer.py
- tests/legacy/test_draw_realisations_from_bundle.py
- tests/legacy/test_load_cmipng.py
> move legacy tests and skip on windows

- mesmer/stats/_auto_regression.py
- tests/unit/test_auto_regression.py
Towards #572. This is only for `fit_auto_regression_monthly` - I am not sure if I should do it for all the auto regression functions or not...  I also think it's not necessary for drawing emulations. Well I can still do it if the need arises...
> fit_auto_regression_monthly: allow sample dim

- CHANGELOG.rst
- mesmer/stats/_linear_regression.py
- tests/integration/test_draw_realisations_mesmer_newcodepath.py
- tests/unit/test_linear_regression.py
> `LinearRegression.predict` allow to select predictors

- CHANGELOG.rst
- docs/source/api.rst
- examples/example_mesmer_m.ipynb
- mesmer/stats/__init__.py
- mesmer/stats/_power_transformer.py
- tests/integration/test_calibrate_mesmer_m.py
- tests/integration/test_draw_mesmer_m.py
- tests/unit/test_power_transformer.py
Not sure if the approach with the subclass is a good API, and whether we should do this at all. And sorry anyway for all these last-minute changes :unamused:
> turn YeoJohnson into a class

- CHANGELOG.rst
- mesmer/stats/_power_transformer.py
- tests/unit/test_power_transformer.py
After #716 it is now possible to add other covariate functions. I may use this for the example.
> YeoJohnson: add constant lambda function

- CHANGELOG.rst
- mesmer/stats/_linear_regression.py
- mesmer/testing.py
- tests/integration/test_calibrate_mesmer_newcodepath.py
- tests/unit/test_linear_regression.py
Addresses https://github.com/MESMER-group/mesmer/pull/521#issuecomment-2995603346. Now the code of `residuals` is ugly :slightly_frowning_face:
> LinReg.residuals: allow DataTree

- CHANGELOG.rst
> MESMER-M: changelog entries for calibrating scen & ens

- .github/workflows/ci-workflow.yml
- CHANGELOG.rst
- ci/requirements/min-all-deps.yml
- docs/source/installation.rst
- mesmer/core/options.py
- pyproject.toml
> drop python 3.10 support

- mesmer/core/datatree.py
- tests/unit/test_datatree.py
I couldn't leave it :disappointed_relieved:
> unpool scen ens

- tests/unit/test_data.py
> load aod: test wrong version

- tests/integration/test_draw_realisations_mesmer_newcodepath.py
> from_netcdf is a classmethod

- CHANGELOG.rst
- docs/source/api.rst
- mesmer/core/volc.py
- mesmer/create_emulations/create_emus_lt.py
- mesmer/create_emulations/create_emus_lv.py
- mesmer/stats/_linear_regression.py
- tests/unit/test_linear_regression.py
- tutorials/tutorial_mesmer_emulating_multiple_scenarios.ipynb
There was less usage than I expected..
> add LinearRegression.from_params(...)

- mesmer/stats/_auto_regression.py
> Reference copy `innovations` into `out` for `draw_auto_regression_monthly_np`

- docs/source/api.rst
- mesmer/__init__.py
- mesmer/distrib/_conditional_distribution.py
- mesmer/distrib/_expression.py
> add mesmer_x symbols to API docs

- CHANGELOG.rst
The next release is v1.0.0 (or maybe v1.0.0rc1) - so update the changelog to reflect this.
> changelog: update target version

- mesmer/datatree.py
- mesmer/io/_load_cmipng.py
- mesmer/stats/_auto_regression.py
- mesmer/stats/_power_transformer.py
- tests/unit/test_auto_regression_scen_ens.py
- tests/unit/test_datatree.py
xarray will update its default in `merge` and `concat` operations
> xarray: new defaults for merge/ concat

- mesmer/testing.py
- tests/unit/test_testing.py
> test `_convert` in testing
