MESMER-group/mesmer

- setup.cfg
- versioneer.py
Ah well black requires a `pyproject.toml` file for configuration. I am not sure if adding this file changes the behavior of ` python setup.py sdist bdist_wheel` so I just set `# fmt: off` in `versioneer.py`.
A alternative would be to use setuptools_scm for the versioning. xarray uses this and it looks kind of neat, but I haven't yet tested that in any project.
> linting: exclude versioneer.py

- CHANGELOG.rst
- docs/environment.yml
- docs/source/installation.rst
- environment.yml
- mesmer/io/load_constant_files.py
- setup.py
- tests/integration/test_calibrate_mesmer.py
- tests/test_phi_gc.py
As suggested in https://github.com/MESMER-group/mesmer/issues/62#issuecomment-901352376 - speed up `calc_geodist_exact` considerably using pyproj. This allows to remove geopy from the list of dependencies. pyproj is a dependency of geopandas which is a dependency of regionmask - might be a good idea to explicitly list it but oh well.
> Speed up geodist

- .github/workflows/ci-cd-workflow.yml
This adds a `conda list` step to the ci. I like to have this to be able to compare installed package versions. Also renames one job from "build" to "test" which I think is better.
> ci: list installed packages

- mesmer/io/_load_cmipng.py
- mesmer/utils/regionmaskcompat.py
Fix two regressions.
1. `concat_dim` has no influence on `"by_coords"` and now raises an error
2. `np.int` is an alias of `int`
> fix a numpy and a xarray deprecation

- setup.py
I double checked - the tests folder was not found as a package because it did not contain a __init__.py file. This makes it explicit.
```bash
tar -tvf dist/mesmer-emulator-*.tar.gz
python -m zipfile --list dist/mesmer_emulator-0.8.2-py3-none-any.whl
```
> setup: only package mesmer

- docs/environment.yml
python 3.10 is not yet ready, pin to py39
> docs: pin python version

- CHANGELOG.rst
- docs/source/api.rst
- docs/source/conf.py
- mesmer/core/linear_regression.py
- mesmer/core/utils.py
- setup.cfg
- tests/integration/test_linear_regression.py
- tests/integration/test_utils.py
- tests/integration/utils.py
> linear regression: add xarray wrapper

- mesmer/__init__.py
- mesmer/core/__init__.py
Added `mesmer/core/__init__.py` which was missing. I did not add it to `mesmer/__init__.py` for now as it's still not public.
> add __init__.py for core

- CHANGELOG.rst
- mesmer/calibrate_mesmer/train_gv.py
numpy v1.22.0 introduces some changes to `np.quantile` it renames the `interpolation` keyword to `method`. This PR restores compatibility with numpy 1.22.
> quantile: rename interpolation kwarg to method

- .github/workflows/ci-cd-workflow.yml
Should abort the GH action workflow when a new commit is pushed.
> GH actions: concurrency

- CHANGELOG.rst
- mesmer/calibrate_mesmer/train_gv.py
- mesmer/calibrate_mesmer/train_lv.py
- mesmer/core/auto_regression.py
- mesmer/core/utils.py
- tests/integration/test_auto_regression.py
- tests/integration/test_utils.py
Adds `_fit_auto_regression_xr` and `_fit_auto_regression_np` - thin wrappers around `statsmodels.tsa.ar_model.AutoReg`.
In contrast to the linear regression I have:
- reworked the internal code by creating a dummy `DataArray` - I think that simplifies the code and looks pretty neat
- not written any 'numerical' tests - it only checks the shape etc. of the results
I am not sure we can follow exactly the same pattern as for the `LinearRegression` class because the coeffs are averaged over the scens. It would be nice to have the same pattern for both but I am not sure which will have to give...
@yquilcaille @znicholls
> add _fit_auto_regression functions

- CHANGELOG.rst
- docs/source/api.rst
- mesmer/calibrate_mesmer/train_lt.py
- mesmer/calibrate_mesmer/train_lv.py
- mesmer/calibrate_mesmer/train_utils.py
Yet another preparation PR for #141 - rewriting & refactoring `train_l_prepare_X_y_wgteq`. I first wanted to to it quick and dirty but https://github.com/MESMER-group/mesmer/pull/141#discussion_r854703265 by @znicholls prompted me to have a closer look at the function. It's not going to be fun to merge this into #141 but I can worry about this later.
In this PR I
- split the original function into two:
- `get_scenario_weights`
- `stack_predictors_and_targets`
- write a helper function to stack predictors and targets
- the stacked arrays are now kept in a dict (instead of an array with an additional dimension)
> refactor stack_predictors_and_targets

- CHANGELOG.rst
- mesmer/core/linear_regression.py
- tests/integration/test_linear_regression.py
This PR adds `fit_intercept` to `mesmer.core.linear_regression`.
`train_gt_ic_OLSVOLC` uses `fit_intercept=False` therefore this needs to be added to `_fit_linear_regression_xr` before we can refactor this code path.
https://github.com/MESMER-group/mesmer/blob/f63fbeb0d9d1318a575e2aa7ad0febc4e675e98f/mesmer/calibrate_mesmer/train_gt.py#L264
---
Open question - how should `intercept` be saved when `fit_intercept=False`?
1. Omit `intercept` from the result
2. As scalar (this is what sklearn does)
3. The same shape as the predictors (this is the current solution)
See details for an example.
<details>
(1) would look like this:
```python
<xarray.Dataset>
Dimensions:        (cell: 3)
Data variables:
tas            (cell) int64 0 1 2
fit_intercept  bool False
```
(2) would look like this: …
> linear_regression: add fit_intercept argument

- CHANGELOG.rst
- mesmer/calibrate_mesmer/train_gt.py
- mesmer/io/load_obs.py
After #144 we can now use `mesmer.core.linear_regression.LinearRegression` in `train_gt_ic_OLSVOLC`.
> use LinearRegression in train_gt_ic_OLSVOLC

- CHANGELOG.rst
- docs/source/api.rst
- mesmer/core/auto_regression.py
- mesmer/create_emulations/create_emus_gv.py
- mesmer/create_emulations/create_emus_lv.py
- tests/integration/test_auto_regression.py
---
A first stab at factoring out 'predicting' an AR process. It does not look very clean to me at the moment but it works.
Comments
- The coefs need to be 2D with shape `n_coefs x n_gridpoints`
- The `covariance` must be passed and not the `standard_deviation`
- `emus_lv_tmp` should be renamed
- `emus_lv_tmp` has shape `n_emus x (n_ts + buffer) x n_cells` - maybe it would be better if this was `n_emus x n_cells x (n_ts + buffer)` (so we can use `@` to multiply and sum, this would require to transpose the coefs)
> add _draw_auto_regression_np

- mesmer/core/auto_regression.py
- tests/integration/test_auto_regression.py
Adds the `lags` as coordinates to the parameters returned in `_fit_auto_regression_xr`.
> fit_auto_regression_xr: add lags to output

- CHANGELOG.rst
- setup.cfg
- setup.py
I wasn't sure what to tackle next so I did some infrastructure maintenance :upside_down_face:
@znicholls what does the `TestCommand` do? Is that something that you use? Is used? Could that be removed or something similar be achieved via `conftest.py`?
The next steps would be to use `setuptools_scm` instead of `versioneer` and add a pyproject.toml file.
> setup options to setup.cfg

- CHANGELOG.rst
- docs/source/api.rst
- mesmer/calibrate_mesmer/train_gv.py
- mesmer/core/__init__.py
- mesmer/core/auto_regression.py
- tests/integration/test_auto_regression.py
- tests/integration/utils.py
This PR extracts `ar_select_order` to its own numpy and xarray wrappers. There are still some open TODOs but I like the pattern that emerges in train_gv.py.
> extract select_ar_order

- mesmer/calibrate_mesmer/train_lv.py
This is a small refactoring of `train_lv_AR1_sci` and `train_lv_find_localized_ecov` before actually doing #153. Helps me understand what happens & should make it slighly faster.
> inplace refactor train_lv.py

- .gitattributes
Another forgotten change from versioneer. For setuptools_scm we want `export-subst` to point at .git_archival.txt in .gitattributes.
> fix .gitattributes for setuptools_scm

- .readthedocs.yml
- docs/source/conf.py
(Should eventually) fix the wrong version number on RTD with the new pyproject.toml etc. installation.
Also cleans up some unused config in docs/conf.py.
---
We might need to go to a manual install - IIRC RTD does something along the lines `python -m pip install . --upgrade-strategy eager` which upgrades packages we pinned (well we did not pin any at the moment but still).
> fix doc version on RTD and small cleanup

- CHANGELOG.rst
- docs/source/api.rst
- mesmer/calibrate_mesmer/train_gt.py
- mesmer/core/smoothing.py
- tests/integration/test_smoothing.py
- tests/integration/utils.py
Spitting out the lowess smoothing. This is much nicer and cleaner again.
> refactor lowess smoothing

- mesmer/calibrate_mesmer/train_lv.py
- mesmer/core/localized_covariance.py
- mesmer/core/utils.py
- tests/integration/test_localized_covariance.py
- tests/integration/test_utils.py
xarray wrapper for `find_localized_empirical_covariance` and `adjust_covariance_ar1`. Ugly as hell but there is no good way to have the same dim more than once for a DataArray.
cc @znicholls
> localized_covariance: add xarray wrapper

- mesmer/calibrate_mesmer/calibrate_mesmer.py
Add `save_params` to `_calibrate_and_draw_realisations` and `_Config`: give (optional) access to all calibrated params (so I can double check the values).
> calibrate_mesmer: add save_params

- mesmer/calibrate_mesmer/train_gt.py
- mesmer/calibrate_mesmer/train_gv.py
- mesmer/calibrate_mesmer/train_lt.py
- mesmer/calibrate_mesmer/train_lv.py
- mesmer/create_emulations/create_emus_gt.py
- mesmer/create_emulations/create_emus_gv.py
- mesmer/create_emulations/create_emus_lt.py
- mesmer/create_emulations/create_emus_lv.py
- mesmer/create_emulations/merge_emus.py
- mesmer/io/save_mesmer_bundle.py
Adds a helper function to save mesmer parameters and emulations (in the pickle format). This is not super important but (1) helps to clean up the code a bit, (2) allows to no longer add `"/"` add the end of path definitions.
> save_mesmer_data helper function

- configs/config_across_scen_T_cmip6ng_test.py
- mesmer/calibrate_mesmer/calibrate_mesmer.py
- mesmer/io/_load_cmipng.py
- mesmer/io/load_constant_files.py
- mesmer/io/load_obs.py
- tests/integration/test_load_cmipng.py
- tests/unit/test_phi_gc.py
Paths can now be given without a trailing separator (`"/"`). This should - in principle - also allow to run mesmer on windows.
> paths: remove need for trailing separator

- CHANGELOG.rst
- mesmer/io/load_constant_files.py
- mesmer/utils/regionmaskcompat.py
- tests/unit/test_regionmaskcompat.py
I found two issues when trying to use `mask_percentage` with xarray objects.
1. The coords were not exactly correct (due to numerical issues)
2. The fractional overlap at the poles was incorrect.
This PR fixes those two problems. Note that the problems were not relevant for mesmer so far! Also adds some basic tests.
I will double check with the author of regionmask if this makes sense.
> mask_frac: rename, fix coords and pole behaviour

- mesmer/core/linear_regression.py
- tests/unit/test_linear_regression.py
Fixes an xarray quirk when some predictors have an extra 0D dimension (e.g. `"height"` for tas). Also raises an error if `dim="predictor"` - this name is currently hard coded.
```python
import xarray as xr
a = xr.DataArray([1, 2], dims="x", coords={"height": 0})
b = xr.DataArray([1, 2], dims="x")
xr.concat([a, b, a], dim="x", join="exact") # fails
xr.concat([a, b, a], dim="x", join="exact", coords='minimal') # works
```
> _fit_linear_regression_xr: small fixes

- CHANGELOG.rst
- mesmer/utils/regionmaskcompat.py
- tests/unit/test_regionmaskcompat.py
Another fix to `mesmer.utils.regionmaskcompat.mask_3D_frac_approx`: passing lat & lon coords _not named_ `"lat"` or `"lon"` now works correctly. The `InvalidCoordsError` change is unrelated but oh well.
Someone tell me to add this functionality to regionmask already...!
> mask_3D_frac_approx: fix passing named cooords

- CHANGELOG.rst
- docs/source/api.rst
- mesmer/__init__.py
- mesmer/xarray_utils/__init__.py
- mesmer/xarray_utils/grid.py
- tests/unit/test_grid.py
---
This is the first of several of PRs which will add helper functions to deal with `Dataset` and `DataArray` objects. This first one deals with converting arrays from regular grids to unstructured grids (i.e. flattening the `lon` and `lat` dimension). What will follow are PRs on masking (land & antarctica), calculating the global mean, and potentially, stacking ensembles, and calculating anomalies.
I do have a number of questions - most of them concerning naming.
---
1. General question: The functions are currently in `mesmer.xarray_utils`. I imagined this as follows:
```python
import mesmer.xarray_utils as mxu
ds = mxu.to_unstructured(ds)
```
Does this sound good? I had a number of other ideas but start to prefer this name - as the functionality is xarray-specific. However, I am open …
> convert grids to/ from unstructured

- CHANGELOG.rst
- docs/source/api.rst
- mesmer/xarray_utils/__init__.py
- mesmer/xarray_utils/mask.py
- tests/unit/test_mask.py
The second one in the series of data manipulation PRs (after #217). This adds functions to mask out the ocean and Antarctica. I think this is quite a bit easier than #217.
The naming of `x_dim` vs. `x_coords` is intentional (compare in #217). For most cases this will not play a role and the two will be the same. However, for regional simulations with a rotated grid it will make a difference. I should probably do a terminology section as for [xarray](https://docs.xarray.dev/en/stable/user-guide/terminology.html).
> xarray_utils: mask ocean and Antarctica

- CHANGELOG.rst
- mesmer/stats/linear_regression.py
- tests/unit/test_linear_regression.py
With this PR it is possible to pass 1D targets to `mesmer.stats.linear_regression.LinearRegression.fit`.
> linear regression: allow 1D targets

- CHANGELOG.rst
- configs/config_across_scen_T_cmip6ng_test.py
- examples/train_create_emus_automated.py
- mesmer/calibrate_mesmer/calibrate_mesmer.py
- mesmer/io/load_constant_files.py
- mesmer/utils/select.py
- tests/integration/test_calibrate_mesmer.py
Similar to to #233 this PR deprecates the `reg_type` param from `load_regs_ls_wgt_lon_lat` and the `reg_dict` param from `extract_land`. Calculating regional means should be part of the postprocessing and not of the calibration and emulation. Also regionmask can handle stacked lat/lon grids (since v0.9, i.e. spring 2022).
At the end of the day I am not entirely sure if this is worth it as it also introduces some complexity and this code path might go away eventually.
> deprecate reg_type

- CHANGELOG.rst
- mesmer/utils/select.py
- tests/unit/test_extract_time_period.py
I wanted to refactor `extract_time_period` so I wrote some tests and then I realized that this function is not used internally, so I deprecated it...
> test, refactor, and deprecate extract_time_period

- mesmer/create_emulations/create_emus_gt.py
- mesmer/create_emulations/create_emus_lt.py
- mesmer/create_emulations/utils.py
I am not sure this actually fixes #27, as it does not remove the `concat_h_f` argument. However, it does refactor the code and I think the logic is now easier to follow. @leabeusch what do you think?
> refactor concat_hist_future

- CHANGELOG.rst
- mesmer/io/_load_cmipng.py
- tests/integration/test_load_cmipng.py
This removes `ref["type"] == "first"` i.e., caculating the anomaly w.r.t. the first ensemble member. Also adds more tests to the data loading and cleans the code/ comments a bit.
> remove ensemble anomaly type 'first'

- CHANGELOG.rst
- docs/source/api.rst
- examples/train_create_emus_automated.py
- mesmer/calibrate_mesmer/calibrate_mesmer.py
- mesmer/create_emulations/create_emus_gt.py
This renames `create_emus_gt` to `gather_gt_data`. I am not sure how good this idea is because (1) it breaks the name symmetry of these functions. The functions should eventually go away i.e. not sure there is much gain to enforce this name change now). But I feel like this is the better name as no emulations are actually created. Somewhat part of #27.
> rename create_emus_gt function

- mesmer/calibrate_mesmer/calibrate_mesmer.py
- tests/integration/test_calibrate_mesmer.py
This makes all arguments to `_calibrate_and_draw_realisations` keyword-only, which allows to remove some that are no longer needed. Also makes the deprecation straightforward.
> _calibrate_and_draw_realisations: kwd only & rm kw

- mesmer/calibrate_mesmer/calibrate_mesmer.py
Follow up to #255 (part of #245) - make args to `_Config` keyword only, with the usual benefits.
> calibrate_mesmer: kw only in cfg (#255 follow up)

- examples/train_create_emus_automated.py
In #254 I adapted examples/train_create_emus_automated.py but forgot to remove a dict access.
> fix example after #254

- .github/workflows/ci-cd-workflow.yml
mamba-org/provision-with-micromamba is being deprecated
> use mamba-org/setup-micromamba for CI

- CHANGELOG.rst
- mesmer/calibrate_mesmer/__init__.py
- mesmer/calibrate_mesmer/calibrate_mesmer.py
- tests/integration/test_calibrate_mesmer.py
Ok I think we are finally there to rename `_calibrate_and_draw_realisations` to `_calibrate_tas`.
> rename _calibrate_and_draw_realisations to _calibrate_tas

- pyproject.toml
- setup.cfg
wheel is no longer a setup requirement, the toml is no longer needed and setuptools is not a runtime requirement
> update setup requirements

- CHANGELOG.rst
- data/README.md
- data/isaod_gl_2022.dat
- environment.yml
- mesmer/calibrate_mesmer/train_gt.py
- mesmer/core/_data.py
- mesmer/io/load_obs.py
- setup.cfg
This has mesmer download and cache the aerosol data using pooch. I went for pooch because I have a bit of experience with it from regionmask. I think this approach should be fine, certainly as long as we stay in the MB range. pooch is added as additional dependency (however, regionmask also has pooch in its list of requirements so it's not really adding anything).
I expect the tests to fail because the data file is currently not yet available at the specified location on github. Maybe I do another PR for this.
> provide aerosol data via pooch

- tests/integration/test_calibrate_mesmer.py
Ignore E721 (do not compare types, use isinstance()) for comparing _two_ unknown types. See https://stackoverflow.com/q/52395064/3010700
> flake8 6.1: ignore E721

- CHANGELOG.rst
- docs/source/api.rst
- mesmer/xarray_utils/grid.py
- tests/unit/test_grid_wrap.py
This functionality is needed again and again (not only in MESMER) - hopefully this implementation is now correct and clean.
@leabeusch & @znicholls: I plan to work intensively on MESMER next week, let's see how that goes. While I am of course always grateful for reviews and name suggestions I might just go ahead to (hopefully) make some progress.
> add longitude wrap functions

- CHANGELOG.rst
- tests/unit/test_grid_wrap.py
Note that the wrap functions do not strictly round trip data that is outside the -180..180/ 0..360 range.
> grid_wrap: roundtrip tests

- mesmer/calibrate_mesmer/calibrate_mesmer.py
The variable name suggested that we are using `tas` and not the "forced global temperature" but it's only a local variable (thus in a separate namespace than the original `tas` variable). Nonetheless - to avoid confusion let's rename it.
> _calibrate_tas: rename confusingly named local variable

- CHANGELOG.rst
- docs/source/api.rst
- mesmer/calibrate_mesmer/train_gt.py
- mesmer/utils/convert.py
Refactor `train_gt` to use `separate_hist_future`. This simplifies and de-duplicates the code. It still looks a bit convoluted, though.
> train_gt: use separate_hist_future

- CHANGELOG.rst
- mesmer/stats/smoothing.py
- tests/unit/test_smoothing.py
Allow missing core dims in `mesmer.stats.lowess`. This will help to pass arbitrary Datasets.
> lowess: allow missing input_core_dim

- CHANGELOG.rst
- mesmer/stats/smoothing.py
- tests/unit/test_smoothing.py
This adds some changes to `mesmer.stats.smoothing.lowess`:
- add `n_steps` keyword, which can be used instead of `frac` (as this is used in mesmer)
- rename `use_coords_as_x` to `use_coords`
- set `use_coords=True` to use coords as x-values per default. For datetime coords this will have to be set to `False` - this is a bit unfortunate (because we will mostly use it for that). However, it's the right thing to do - we want to be explicit about not using the coords (important when they are not equally spaced).
> lowess: n_steps and use_coords

- mesmer/create_emulations/__init__.py
`_convert_raw_mesmer_to_xarray` was not available from the main name space
> create_emulations: add missing import

- CHANGELOG.rst
- mesmer/core/computation.py
- mesmer/io/load_constant_files.py
- tests/unit/test_computation.py
- tests/unit/test_phi_gc.py
Allow passing `xr.DataArray` to `gaspari_cohn`. Maybe this needs a check such that no `Dataset` is passed? - Done.
This was motivated by looking at #109 again.
> gaspari_cohn: allow passing xr.DataArray

- CHANGELOG.rst
- mesmer/core/computation.py
- mesmer/stats/localized_covariance.py
- tests/unit/test_computation.py
- tests/unit/test_phi_gc.py
Similar to #296: allow passing `DataArray` to `calc_geodist_exact`. Again I am keeping this in `computation` for the moment. Should probably go to `mesmer.geospatial`.
Again, inspired by #109. Thanks @znicholls
> calc_geodist_exact: allow passing DataArray

- CHANGELOG.rst
- mesmer/core/computation.py
- tests/unit/test_computation.py
Add function to calculate Gaspari-Cohn correlation matrices for a range of localisation radii. Again, blatantly stolen from #109, so @znicholls should really get the credit here. I pass `geodist` instead of `lon, lat` because I still intend to do #62 and for this it is much easier if we pass the geodist directly. Makes it also a bit more explicit what is happening.
The tests are crap - they repeat the code in the function, which renders almost worthless. Still it checks that it is run.
> add calc_gaspari_cohn_correlation_matrices

- mesmer/calibrate_mesmer/train_lt.py
- mesmer/calibrate_mesmer/train_lv.py
- mesmer/create_emulations/create_emus_gv.py
> add comments from #109

- mesmer/core/utils.py
- tests/unit/test_utils.py
Add helper function to check if time coords are annual. Will be used to align the model and aod data.
> assert_annual_data helper function

- mesmer/calibrate_mesmer/train_gv.py
I was playing around with #109 when I noticed some tests randomly failing. Took me too long what's going wrong. Writing a test for this would be a pain...
One thing I noticed - the way it is set up, we select `AROrder = 1` for the following situation:
```
order
scenario ensemble_member       
hist     r1i1p1f1             1
r2i1p1f1             2
ssp126   r1i1p1f1             2
r2i1p1f1             2
```
`arr.quantile(q=0.5, method="nearest")` over the scenarios selects `[1, 2]` and from this we select 1. (However, rounding up is no better, because then we could end up selecting 2 for (3 x 1 and 1 x 2). I may have to open an issue for this. Maybe it's also only relevant in this artificial scenario...
> fix ar order selection

- mesmer/testing.py
Small improvement for `assert_dict_allclose`. Unfortunately you cannot pass `err_msg` to `xr.testing.assert_allclose` (but then again xr Variables are named...)
> assert_dict_allclose: add err_msg

- CHANGELOG.rst
- mesmer/calibrate_mesmer/train_gv.py
- mesmer/calibrate_mesmer/train_lv.py
- mesmer/stats/auto_regression.py
- tests/unit/test_auto_regression.py
Despite #307 I want to get this in. As always unsure if that should be `cov` or `covariance`.
> auto_regression: return covariance

- CHANGELOG.rst
- mesmer/core/mask.py
- tests/unit/test_mask.py
We are working with the coords so we need to check that the coords are in the DataArray and not the dims.
> fix mask_ocean for 2D grids

- CHANGELOG.rst
- mesmer/create_emulations/create_emus_gv.py
- mesmer/create_emulations/create_emus_lv.py
- mesmer/stats/auto_regression.py
- tests/unit/test_auto_regression.py
A lot is still missing (tests, docs). But as a first draft.
> xarray wrapper to draw auto-regression samples

- CHANGELOG.rst
- ROADMAP.md
- docs/source/api.rst
- docs/source/development.rst
- examples/config_tas_cmip6ng_example.py
- examples/train_create_emus_automated.py
- mesmer/calibrate_mesmer/train_gt.py
- mesmer/calibrate_mesmer/train_gv.py
- mesmer/calibrate_mesmer/train_lt.py
- mesmer/calibrate_mesmer/train_lv.py
- mesmer/core/computation.py
- mesmer/core/grid.py
- mesmer/core/utils.py
- mesmer/core/weighted.py
- mesmer/create_emulations/create_emus_gv.py
- mesmer/create_emulations/utils.py
- mesmer/io/_load_cmipng.py
- mesmer/io/load_mesmer.py
- mesmer/io/save_mesmer_bundle.py
- mesmer/stats/linear_regression.py
- mesmer/stats/localized_covariance.py
- setup.cfg
- tests/unit/test_grid.py
- tests/unit/test_linear_regression.py
- tests/unit/test_utils.py
fix some typos (using [codespell](https://github.com/codespell-project/codespell)). Called using:
```bash
codespell --skip=".git,.mypy_cache,*.tex,*.ipynb,./docs/build,./build" --ignore-words-list varn  -w -i 3
```
(to extend the word list, separate by comma, e.g., `varn,mod`)
> fix typos (using codespell)

- examples/config_tas_cmip6ng_example.py
- mesmer/calibrate_mesmer/calibrate_mesmer.py
- tests/integration/test_calibrate_mesmer.py
Another minor cleanup (after #267)
> remove references to observations_root_dir (dir_obs)

- CHANGELOG.rst
- docs/source/api.rst
- docs/source/development.rst
- examples/train_create_emus_automated.py
- mesmer/calibrate_mesmer/calibrate_mesmer.py
- mesmer/io/_load_cmipng.py
Added `load_cmip_data_all_esms` helper function.
> add `load_cmip_data_all_esms` helper function

- mesmer/calibrate_mesmer/train_gv.py
- mesmer/stats/localized_covariance.py
Removes 0.5s from `import mesmer` (about 40%). Could be made even faster by moving the imports of pooch and regionmask, but that would require moving several statements.
```
import mesmer
```
```bash
python -X importtime import.py 2> import.log
tuna import.log
```
> speed up import

- CHANGELOG.rst
- mesmer/stats/smoothing.py
- tests/unit/test_smoothing.py
Add `combine_dim` argument to `lowess` so data can be pooled to estimate the lowess smoothing. This will probably never be used, but I only realized this once I finished implementing it...
> lowess: allow to pool along dim

- mesmer/core/utils.py
- tests/unit/test_linear_regression.py
- tests/unit/test_smoothing.py
- tests/unit/test_utils.py
Allows the following:
```python
mesmer.core.utils._check_dataarray_form(da, ndim=(1, 2))
```
> check_dataarray_form: can pass several ndims

- mesmer/core/_data.py
- tests/unit/test_data.py
> ensure aod data is not altered in-place

- CHANGELOG.rst
- docs/source/api.rst
- mesmer/calibrate_mesmer/train_gv.py
- mesmer/calibrate_mesmer/train_lv.py
- mesmer/create_emulations/create_emus_gv.py
- mesmer/create_emulations/create_emus_lv.py
- mesmer/stats/auto_regression.py
- tests/unit/test_auto_regression.py
Rename the auto regression functions to a public name. I don't particularly like that I have a different approach for the linear regression and the auto regression - but I don't know which is better, so keep this for now.
> make AR functions public

- CHANGELOG.rst
- docs/source/api.rst
- mesmer/__init__.py
- mesmer/core/geospatial.py
- mesmer/io/load_constant_files.py
- mesmer/stats/__init__.py
- mesmer/stats/gaspari_cohn.py
- tests/unit/test_computation.py
This renames the geodist and gaspari_cohn functions. I am still not sure if the names are good :slightly_frowning_face:
> move and rename geodist and gaspari_cohn

- CHANGELOG.rst
- mesmer/stats/_linear_regression.py
- tests/unit/test_linear_regression.py
I need to think a bit more about this - I wrote this so we can split up the linear regression. However, this will include the intercept twice. So I may have to add the possibility to add the `intercept` in `exclude`.
```python
if "intercept" in exclude:
prediction = xr.zeros_like(params.intercept)
else:
prediction = params.intercept
```
> lin reg: add exclude to predict

- mesmer/stats/_linear_regression.py
- tests/unit/test_linear_regression.py
Explicitly print the missing & superfluous predictors in `LinearRegression.predict`.
> lin reg: mention missing & superfluous predictors

- .github/workflows/ci-cd-workflow.yml
- CHANGELOG.rst
- docs/source/installation.rst
- setup.cfg
> drop python 3.7 support

- mesmer/__init__.py
- mesmer/stats/_auto_regression.py
- tests/unit/test_smoothing.py
Moving to python 3.8+ allows some simplifications. Also the lowest xarray version supporting py3.8 is v2022.03.0 which allows further code clean ups. Could have done this in #365...
> upgrade code to pyhon 3.8 and xarray 2022.03

- .github/workflows/ci-cd-workflow.yml
- CHANGELOG.rst
- docs/source/installation.rst
- mesmer/core/grid.py
- mesmer/core/utils.py
- mesmer/stats/_linear_regression.py
- setup.cfg
- tests/unit/test_grid.py
I only wanted to do this later but it will not really matter...
> drop python 3.8 support

- .github/workflows/ci-cd-workflow.yml
- CHANGELOG.rst
- setup.cfg
> test on python 3.12

- .github/workflows/pypi-release.yaml
releasing manually was tedious (had to ensure I don't delete my devel folder and required a token via 2FA). This uses the GHA workflow from xarray to automate this. Requires a "Trusted Publisher" on pypi and test.pypi (which I just set up). I am not sure how I can test this, though :shrug:
> GitHub action for publishing to PyPI

- .github/workflows/ci-cd-workflow.yml
We now have a dedicated workflow uploading to pypi copied from xarray (see #373 and #374). Uses "Trusted Publisher" on pypi (see https://pypi.org/manage/project/mesmer-emulator/settings/publishing/). It uploads to pypi when creating a release with the tag name `"v.*"`.
FYI @znicholls
> remove unused deploy-pypi workflow

- tests/unit/test_weighted.py
These calls are not necessary... and are now broken on the newest version of xarray (see pydata/xarray#8679)
> weighted: clean tests

- environment.yml
- examples/config_tas_cmip6ng_example.py
- mesmer/calibrate_mesmer/calibrate_mesmer.py
- mesmer/stats/_gaspari_cohn.py
- scripts/test_install.py
- setup.cfg
> use black 24

- mesmer/stats/_gaspari_cohn.py
> refactor Gaspari Cohn to accelerate it

- CHANGELOG.rst
- mesmer/core/_data.py
- tests/unit/test_data.py
- tests/unit/test_utils.py
Updates for pandas v2.2 and xarray v2024.02:
- pandas made some changes to the date parsing in `read_csv`
- pandas and xarray made changes to the frequency strings (e.g. `"A"` -> `"YE"`)
- also we set the minimum xarray version at v2023.04
For this PR it is now very helpful that we merged #398. (There may, however, be some intermediate xr & pd combinations that still create warnings)
> updates for pandas v2.2 and xarray v2024.02

- mesmer/stats/_auto_regression.py
- tests/integration/test_load_cmipng.py
- tests/unit/test_grid.py
numpy v2.0 removes `np.NaN` of favor of `np.nan`
> numpy 2 compatibility

- mesmer/mesmer_m/harmonic_model.py
In the harmonic model `generate_fourier_series` we passed the order as an argument instead of inferring it from the length of the coefficients array. This is changed here. Additionally, I reordered the arguments to facilitate testing on xarrays.
> Infer harmonic model order from coefficients

- mesmer/mesmer_m/power_transformer.py
Renamed i and j indexes to gridcell and year for better readability in `PowerTransformerVariableLambda.transform()` and `inverse_transform`.
> rename i and j in power transformer transform & inverse transform

- mesmer/mesmer_m/harmonic_model.py
In the harmonic model we return the fit coefficient array with nans, for coefficients, higher than the order we chose. We need to fill the array up until the max order, so we have coefficient arrays of the same length for all gridcells, so filling the array up with nans for unfit coefficients might have made sense in the beginning. However, imo it makes more sense to fill it up with zeros because in this way one can still use the fit coefficient array to `generate_fourier_series` and it makes testing easier, see #431.
> allow nans in generate harmonic model sum

- mesmer/mesmer_m/harmonic_model.py
Fix for mistake made in #433. `nansum` needs an axis to sum along, otherwise it will just sum over all dimensions and output a single number.
> add axis = 0 for nansum

- mesmer/mesmer_m/power_transformer.py
The bounds for the fit of lambda should be positive for the first coefficient, to have a logistic lambda function. Also rewrote it as a normal array.
A step towards solving #440
> adjust bounds of power transformer fit

- mesmer/mesmer_m/power_transformer.py
Using rosen_der for the Jacobian in the power transformer optimization lead to instabilities in the fit, see discussion in #440
> remove jac=rosen_der for from power transformer optimization

- mesmer/mesmer_m/power_transformer.py
Changing the comparison to eps in `_yeo_johnson_transform` to be consistent with [sklearn's yet-johnsons power transform](https://github.com/scikit-learn/scikit-learn/blob/8721245511de2f225ff5f9aa5f5fadce663cd4a3/sklearn/preprocessing/_data.py#L3396).
> align equality check in yeo johnson transform

- CHANGELOG.rst
- mesmer/core/mask.py
- mesmer/core/regionmaskcompat.py
- mesmer/io/load_constant_files.py
- tests/unit/test_regionmaskcompat.py
regionmask 0.12.0 offers it's own implementation of `mask_3D_frac_approx`, so at some point we can remove this function from mesmer. This takes the first step by marking it as deprecated.
> deprecate mask_3D_frac_approx

- docs/source/index.rst
Currently our landing page looks a bit strange - some parts of the index is hidden, some part is not, and there are two titles (one above and one below the index) see https://mesmer-emulator.readthedocs.io/en/v0.10.0/.
This PR hides the whole index, relegating it entirely to the side bar. Then it only shows the readme text, which makes much more sense. (Moving `.. include:: ../../README.rst` up is just a formality).
> docs: clean landing page

- .readthedocs.yml
- docs/environment.yml
This adds all of our direct dependencies to the docs environment (following #448) but removes the transitive ones. The direct ones were installed before, just not explicitly listed. Unfortunately sphinx (or maybe just the autosummary extension) imports the functions it wants to create the docs for, so they _must_ be installed. However, leaving the optional transitive deps away should lead to a small speed up.
---
Alternatively we could install everything using pip but that would be more work (c.f. regionmask/regionmask#450)
> RTD: remove transitive deps from docs env

- mesmer/mesmer_m/power_transformer.py
Changing the method in optimize.minimize` to Nelder-Mead from SLSQP should make the coefficients fit more stable, see https://github.com/MESMER-group/mesmer/issues/440#issuecomment-2127172434
> change optimize.minimize method from SLSQP to Nelder-Mead

- mesmer/mesmer_m/harmonic_model.py
- tests/unit/test_harmonic_model.py
> Harmonic model return residuals

- mesmer/mesmer_x/OLD_train_l_distrib.py
- mesmer/mesmer_x/create_emus_l_distrib.py
- mesmer/mesmer_x/temporary_config_all.py
- mesmer/mesmer_x/temporary_support.py
- mesmer/mesmer_x/train_l_distrib_mesmerx.py
- mesmer/mesmer_x/train_utils_mesmerx.py
This PR
- reflows comments, docstrings and some of the strings
- moves the class docstring to `__init__` (which is recommended https://peps.python.org/pep-0257/ & allows velin to know the params and fix the format)
- does not change any code
There is certainly more to be done here but I will defer that for later. I will also merge more or less right away because I want to open anther PR with some initial code changes.
> MESMER-X: reflow and fix comments and docstrings

- mesmer/mesmer_x/train_l_distrib_mesmerx.py
Created a decorator to suppress the warnings. This allows to avoid a level of indentation, unfortunately there is not much that is unwrapped. But should become slightly easier to read anyway. We absolutely need to be more specific which warnings we suppress, because currently we also miss deprecations and other warnings we want to see - but have to defer that until we have some running tests to see what warnings there are. github does not seem to get the correct diff...
> MESMER-X: decorator to supress warnings

- mesmer/mesmer_x/train_l_distrib_mesmerx.py
The `Expression` class defines `coefficients_list` and not `list_coefficients` - or did I miss something?
https://github.com/MESMER-group/mesmer/blob/02169332a342275bf7e12db0dade60b5312ecc93/mesmer/mesmer_x/train_utils_mesmerx.py#L192
> FIX: list_coefficients -> coefficients_list

- CHANGELOG.rst
- mesmer/stats/__init__.py
- mesmer/stats/_auto_regression.py
- tests/unit/test_auto_regression.py
Similar to MESMER, we also use an AR1 process to emulate local variability in MESMER-M. However, we cannot recycle the original AR functionalities since MESMER-M fits AR parameters for each month individually (➡️ how does June depend on May, how does July depend on June?). In this PR I add the functionalities to achieve this.
> add monthly AR1 process utilities

- mesmer/stats/_auto_regression.py
Since we are requiring python 3.9+ now, we can use the shorter dict union formulation here.
> switch to new dict union in autoregression

- CHANGELOG.rst
- mesmer/stats/__init__.py
- mesmer/stats/_localized_covariance.py
- tests/unit/test_localized_covariance.py
Add a wrapper around `find_localized_empirical_covariance` to produce a covariance matrix for every month to use for MESMER_M
> add wrapper for finding monthly localized covariance

- CHANGELOG.rst
- mesmer/stats/__init__.py
- mesmer/stats/_auto_regression.py
- tests/unit/test_auto_regression.py
We want to return the residuals of the cycle-stationary AR(1) process to fit the covariance matrix on these. This removes the need for bounds in the fit as well as `predict_auto_regression`.
> Remove bounds on cyclo-stationary AR(1)

- .github/PULL_REQUEST_TEMPLATE.md
- .pre-commit-config.yaml
- CHANGELOG.rst
- Makefile
- docs/source/development.rst
- environment.yml
- mesmer/io/load_constant_files.py
- mesmer/mesmer_x/OLD_train_l_distrib.py
- mesmer/mesmer_x/temporary_config_all.py
- pyproject.toml
- setup.cfg
- tests/unit/test_power_transformer.py
Add ruff configuration. I don't necessarily want to switch but we could...
> use ruff for code linting

- CHANGELOG.rst
- mesmer/stats/_power_transformer.py
- tests/unit/test_power_transformer.py
With this we can take another stab at #476. It also seems a bit faster. Modeled after scikit-learn/scikit-learn#26188
> more stable yeo johnson roundtrips

- mesmer/stats/_power_transformer.py
This reduces the computation of `mesmer.stats.fit_yeo_johnson_transform` to below 10s. Still not blazingly fast but a bit faster with an acceptable increase in complexity (IMO). #494 helped as I could see that all four cases require `np.log1p(np.abs(data))` (which is constant), so we can pre-compute that in one go (instead doing it every iteration with semi-costly indexing shenanigans). Similarly, it seems faster to create intermediate arrays instead of indexing them twice (`lmbds`).
I did not optimize `_yeo_johnson_inverse_transform_np` because it is not used in the inner loop of the optimization and thus much less critical.
I hope I got all signs correct :man_shrugging:
> yeo-johnson: performance optimization

- tests/unit/test_auto_regression.py
- tests/unit/test_harmonic_model.py
Avoid some warnings in the tests. I am pretty sure `"YE"` is also fine for older versions of pandas/ xarray but should probably run with #503 merged, so marking as draft for now.
> date_range: update freq string

- .github/workflows/ci-workflow.yml
Follows the instruction at https://docs.codecov.com/docs/adding-the-codecov-token
(I admit opening a issue for this was probably overkill...)
> GHA: use codecov token

- mesmer/stats/_harmonic_model.py
- tests/unit/test_harmonic_model.py
I think `order` is more descriptive than `n_sel`. We could also go for `selected_order`
Is there a reason we choose `n_sel` that I forgot about?
> fit_harmonic_model: n_sel -> selected_order

- .github/workflows/ci-workflow.yml
- CHANGELOG.rst
- ci/requirements/min-all-deps.yml
- docs/source/installation.rst
- mesmer/core/_data.py
- mesmer/core/utils.py
- mesmer/stats/_auto_regression.py
- mesmer/stats/_linear_regression.py
- mesmer/testing.py
- pyproject.toml
- setup.cfg
[SPEC 0](https://scientific-python.org/specs/spec-0000) suggests we can drop python 3.9. So let's do that.
1. I removed the CI for 3.11 on purpose - I think testing 3.10 and 3.12 is enough (I never really had a failure due to the python version).
2. I did not know that a new syntax is supported for `isinstance` - interesting
```diff
- isinstance(3, (int, str))
+ isinstance(3, int | str)
```
> drop python 3.9 support

- CHANGELOG.rst
- mesmer/stats/_harmonic_model.py
- tests/unit/test_harmonic_model.py
Make our fourier series more consistent with the standard usage (e.g. on wikipedia for the fourier series or in numpy for fft<sup>1</sup>), [defined as](https://en.wikipedia.org/wiki/Fourier_series#math_Eq.2):
$$s_N(x) = A_0 + \sum_{n=1}^N \left(A_n \cos \left(2 \pi \tfrac{n}{P} x \right) + B_n \sin \left(2 \pi \tfrac{n}{P} x  \right) \right)$$
So this PR does two things:
1. switch the order of $\cos$ and $\sin$ so that $A_n$ is associated with $\cos$
2. use fractional years from $0...\frac{11}{12}$ instead of $\frac{1}{12}...1$. Note that this is nothing more than a phase shift with an angle of -30°. This phase shift leads to different values for $A_n$ and $B_n$ but to the same generated series.
<sup>1</sup> well fft uses the exponential form but that's equivalent
> fourier series: more consistent with standard definition

- CHANGELOG.rst
- mesmer/stats/_harmonic_model.py
- tests/unit/test_harmonic_model.py
Performance optimization of `_generate_fourier_series_np`. Builds on #512 so the diff is actually smaller. This does two main things:
1. `cos(alpha)` is periodic - so we only need to compute it once for each month (instead of `n_years * 12` times). We then reshape the `yearly_predictor` to `n_years x 12` such that broadcasting ensures each element is multiplied with the coefficients
2. Change the order of operation: sum the coefficients before multiplying - this avoids a lot of multiplication and sum operations. So instead of
$$\sum\left((a_i \cdot T + b_i) \cdot \cos(\alpha) + (c_i \cdot T + d_i) \cdot \sin(\alpha)\right)$$
we do
$$\sum\left(a_i \cdot \cos(\alpha) + c_i \cdot \sin(\alpha)\right) \cdot T + \sum\left(b_i \cdot \cos(\alpha) + d_i \cdot \sin(\alpha)\right)$$
This speeds up …
> performance optimize `_generate_fourier_series_np`

- mesmer/stats/_power_transformer.py
- tests/unit/test_power_transformer.py
This would be a step towards #517 - gather the coeffs in an array instead of different variables. This should make it agnostic to the number of coeffs there are.
What I am not happy is the naming (as always) - the DataArray is now named `coeffs` and it has a dimension named `coeff` - that is not good but would be a good name? :face_in_clouds:
> power transformer: coeffs as array

- tests/integration/test_calibrate_mesmer_x.py
I am regularly running `pytest .` and want to be able to keep doing that. A runtime of ~2 min is too long for that, so I have to mark this test as slow as well. Optimally would speed this up considerably, but that is for another time ;-)
This test still runs on GHA
> mesmer-x integration test: mark both as slow

- mesmer/mesmer_x/train_utils_mesmerx.py
- tests/unit/test_mesmer_x_expression.py
As correctly guessed by @veni-vidi-vici-dormivi in https://github.com/MESMER-group/mesmer/pull/526#pullrequestreview-2317904070 I want to disallow passing bare functions to an expression, e.g. `loc=mean()`. This function would then be translated to `loc=np.mean()`.
@yquilcaille would like to keep this functionality (https://github.com/MESMER-group/mesmer/pull/526#issuecomment-2363569175).
I still want to remove it because it's **not difficult to fix** for the user, but difficult to explain and not obvious what happens. Removing also makes the code easier to understand.
> `Expression`: disallow bare functions

- mesmer/mesmer_x/train_utils_mesmerx.py
- tests/unit/test_mesmer_x_expression.py
Added tests for `expr.evaluate` - I will do some more refactoring of the method later but wanted to get some tests in first.
> `Expression`: test `evaluate` method

- mesmer/mesmer_x/train_utils_mesmerx.py
We can pass `locals` ("locally defined variables") as argument to `eval` - this avoids `exec` and "magically defined variables". I think this helps a lot with the readability of the code.
- `locals` is a positional-only argument, so the `None` is required
- as `coefficients_values` or `inputs_values` can be a `Dataset` we cannot use dict union (`d1 | d2`) and need to splat them
- I suggest to merge #534 first so to have the tests first (therefore only draft PR at the moment)
> `Expression.evaluate`: avoid `exec` by using `locals`

- mesmer/mesmer_x/train_l_distrib_mesmerx.py
- mesmer/mesmer_x/train_utils_mesmerx.py
- tests/unit/test_mesmer_x_expression.py
This creates a separate method to `evaluate_params` - so we don't necessarily create the frozen distribution. E.g. if we only need `params["loc"]` we can save the slow creation of the distribution.
This saves about 1-2 minutes on the tests already (about 20% - 25%).
Only a draft PR for now
- it's on top of #535 - so waiting for that to be merged first
- the tests need to be updated
- needs docs
> `Expression`: split out `evaluate_params`

- CHANGELOG.rst
- mesmer/mesmer_x/train_l_distrib_mesmerx.py
- tests/unit/test_mesmer_x_distrib_cov.py
> MESMER-X: Test `distrib_cov`

- .github/workflows/upstream-dev-ci.yaml
- ci/install-upstream-wheels.sh
- tests/unit/test_smoothing.py
This PR tests the development versions of our dependencies. This gives us more time if they introduce a breaking change and also helps to catch bugs in upstream dependencies. We don't update all the (indirect) dependencies (e.g. regionmask would depend on geopandas). The approach here is to install the current version, then remove it and install it with pip. The first step is done so we have all dependencies present.
That usually goes wrong the first time...
> CI: test upstream dev

- ci/requirements/min-all-deps.yml
- docs/source/installation.rst
- environment.yml
- setup.cfg
This PR adds xarray-datatree to the dependencies to work towards #106
> Add xarray-datatree dependency

- ci/install-upstream-wheels.sh
- environment.yml
- setup.cfg
See discussion in https://github.com/MESMER-group/mesmer/pull/556#issuecomment-2464978340
> xarray: add upper pin for datatree compatibility

- .github/workflows/ci-workflow.yml
- .github/workflows/upstream-dev-ci.yaml
- ci/requirements/min-all-deps.yml
- environment.yml
Runs the tests in parallel. Can be called as
```bash
pytest -n auto ... # auto select number of cores
pytest -n 4 ... # set number of cores
```
While in theory very nice it does actually not speed up the tests locally. This surprises me but is maybe because the individual tests take a bit longer due to multi-threading issues. Let's see what happens on GHA. For some reason pytest-xdist is already in setup.cfg.
> tests: run in parallel

- mesmer/testing.py
- tests/unit/test_testing.py
A helper function to check if two arrays are close, but allows a number of failures. This could help with #501 where most of the array is close but some points are not & expect this could become more important? Uses the numpy machinery, thus does not work with xarray. However, there is no `isclose` function for `DataArray` and `Dataset` and `xr.testing.assert_allclose` is a mess.
See also `np.testing.assert_allclose??`
> testing: assert_allclose with allowed failures

- mesmer/stats/_power_transformer.py
- tests/unit/test_power_transformer.py
Does what it says.
---
What is a bit inconsistent but also makes sense: the transformed residuals have dims `time, gridcell` while the and the `lambdas` have dims `month, gridcell, year`.
---
edit: only the `lambdas` do, the `lambda_coeffs` have dims `month, gridcell, coeff`
> fit_yeo_johnson_transform: add month coords

- setup.cfg
Shows the timing of the 10 slowest tests each time the tests are run. I wasn't sure if I should only add this for the CI :man_shrugging: (i.e. add to the pytest call in ci-workflow.yml)
> show timing of slowest tests

- .github/workflows/upstream-dev-ci.yaml
upstream dev CI failed but no issue was created because there was the wrong repo owner... (I copied that from regionmask where the organization is also called regionmask)
---
As for why it failed - no idea. I had hoped this was fixed for good with https://github.com/MESMER-group/mesmer/pull/516/files#r1742290021 That optimization seems to still be brittle :-( let's see if it turns up again tonight
> CI: fix upstream-dev issue-from-pytest-log

- mesmer/stats/_harmonic_model.py
Found another couple of performance optimizations. The most important is caching `cos_sin`. I knew that last time but did not think of using an `lru_cache` which makes the second call almost free (`50 ns` vs `10 μs` for `order=6`; which equals about 1/3 of the total time of `_generate_fourier_series_np`). Also not truncating coeffs (when known not to contain `nan`) and using `ravel` brings another ~5% each. However, it's not super visible in the timing of the tests...
> harmonic model: more performance optimization

- mesmer/stats/_harmonic_model.py
Relax the condition for a perfect `mse` in the selection of the harmonic model order. This is necessary because (1) there are some numerical inaccuracies when calculating a product-sum using `@` (2) the upcoming scipy release, which seems to add a bit of inaccuracy as well...
Note: the abort condition uses `<` (and not `<=`) thus the second `-np.inf` stops the search, which is the correct choice.
https://github.com/MESMER-group/mesmer/blob/598e2673c644a84a632e5387b0090ee1411d352c/mesmer/stats/_harmonic_model.py#L232
> harmonic model: relax 'perfect' mse

- ci/requirements/min-all-deps.yml
- docs/source/installation.rst
- environment.yml
Add filefishes dependency to facilitate loading several scenarios and ensemble members for #537
> Add filefisher dependency

- ci/requirements/min-all-deps.yml
- environment.yml
this version patches a bug in a function that we want to use in #537
> bump filefisher dependency to v1.0.1

- docs/source/conf.py
- pyproject.toml
Minimal mypy configuration - note it does not pass `mypy .` Many of these errors will be fixed by #587 and I may take care of the rest afterwards. But I doubt we will ever have complete type hints... and also mypy and pyright (or pylance) can disagree on stuff...
> add mypy configuration

- CHANGELOG.rst
- mesmer/mesmer_x/train_l_distrib_mesmerx.py
- tests/unit/test_mesmer_x_first_guess.py
Before there was check hindering `thresh_min_proba` to be `None` even though this can be useful, for example for the `truncnorm`, see the issue below.
> Enable `thresh_min_proba` to be `None`

- CHANGELOG.rst
- mesmer/mesmer_x/train_l_distrib_mesmerx.py
- tests/unit/test_mesmer_x_distrib_cov.py
- tests/unit/test_mesmer_x_first_guess.py
Some distributions do not use `loc` and `scale`. While all distributions have `loc` as parameter, for some it might make sense to set it to 0 like the beta distribution or even just if one has calculated residuals for their data and knows the loc is 0. Thus, I implemented an option to set the location in the expression to a certain value (note because of #525 it can only be ints atm). Moreover, the discrete distributions tend to not have a scale parameter so I made it optional.
> Enable that location and scale parameters might be set or not used.

- CHANGELOG.rst
- mesmer/mesmer_x/train_l_distrib_mesmerx.py
When we use `option_NelderMead == "best_run"` for `distrib_cov._minimize()` we want to select the parameters that yield the least loss between minimizing with Powell or with Nelder-Mead. Until now, if the fit using Powell (`fit`) failed, `fit.fun` would be `nan` and thus the test if the Nelder Mead fit (`fit_NM`) was better `fit_NM.fun < fit.fun` would yield ` False and `fit_NM` was discarded.
> distrib_cov._minimize: also use `fit_NM` for "best_run" if fit.success is False

- CHANGELOG.rst
- mesmer/mesmer_x/train_l_distrib_mesmerx.py
- tests/unit/test_mesmer_x_first_guess.py
Discrete distributions don't have logpdf but instead a logpmf. We already use the logpmf in `distrib_cov.loglike()` but  we do not reuse this function here because we need an exponent. Thus I added the logpmf for discrete distribution which enables us to also test some of these.
> distrib_cov._fg_fun_LL_n(): add logpmf for discrete distributions

- mesmer/stats/_auto_regression.py
- tests/unit/test_auto_regression.py
Adds capacity to draw several scenarios also with `draw_autoregression_monthly` and tests all `draw_autoregresion_*` functions with a `DataTree`.
> Test `draw_auto_regression_*` with `DataTree` of seeds

- CHANGELOG.rst
- mesmer/mesmer_x/train_l_distrib_mesmerx.py
- mesmer/mesmer_x/train_utils_mesmerx.py
This avoids `Expression.evaluate(...)` in favor of `Expression.evaluate_params(...)`, which leads to a approximately 2x-4x speedup of calibrating mesmer-x. Instead of adding many methods to `Expression` it calls the method on `Expression.distr` (e.g. `Expression.distr.pdf(x, **params)`. 
cc @l-pierini, @yquilcaille
> MESMER-X: use params instead of distr

- CHANGELOG.rst
- mesmer/mesmer_x/train_utils_mesmerx.py
- tests/unit/test_mesmer_x_expression.py
I am very confident that the scalars don't need to be broadcast, which will save some more seconds.
> MESMER-X: keep scalars

- CHANGELOG.rst
- mesmer/mesmer_x/train_utils_mesmerx.py
Another way to speed up MESMER-X. 
```python
import numpy as np
c1 = 2.558745
tas = np.array([1.3, 4])
a = "c1"
a_compiled = compile(a, "", "eval")
b = "c1 * tas"
b_compiled = compile(b, "", "eval")
%timeit eval(a)
%timeit eval(a_compiled)
%timeit eval(b)
%timeit eval(b_compiled)
```
```
5.23 μs ± 70.8 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
411 ns ± 8.39 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
9.53 μs ± 615 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)
1.42 μs ± 41.7 ns per loop (mean ± std. dev. of 7 runs, 1,000,000 loops each)
```
> MESMER-X: compile expression

- CHANGELOG.rst
- ci/requirements/min-all-deps.yml
- mesmer/core/_data.py
- mesmer/core/utils.py
- setup.cfg
- tests/unit/test_auto_regression.py
- tests/unit/test_data.py
- tests/unit/test_harmonic_model.py
- tests/unit/test_utils.py
Especially requiring `xarray >=2024.2` and `pandas >= 2.2` allows to remove the frequency string adaptations.
#607 will also need the _newest_ xarray version (but that's not yet relevant).
@l-pierini @yquilcaille: FYI (but you should probably not need to update your environment).
> bump dependencies

- CHANGELOG.rst
- docs/source/api.rst
- mesmer/__init__.py
- mesmer/core/anomaly.py
- tests/integration/test_calibrate_mesmer_newcodepath.py
- tests/unit/test_anomaly.py
Adds a helper function to calculate anomalies, which hides not-nice `xr.DataTree` workaround. Turns out this is all nice and dandy until you think about all the ways this could fail. So if an member is missing from the historical simulation it silently removes it from the scenario (inner join). Testing that up-front is annoying (because we don't know the name of the ensemble dimension) so we compare the coords of the anomaly with the original ones.
Also here we see some stuff that is nicer on the new datatree implementation, e.g. a way to iterate over two or more trees (`group_subtrees`). There is some incompatibility in the tests which I don't bother to fix.
> add anomaly function

- mesmer/core/volc.py
This is a mini nit and actually up to personal preference. I felt that passing the temperature data to the aod routines `_predict_volcanic_contributions` and `_load_and_align_strat_aod_obs` is unnecessary and a bit confusing. The data is not actually needed in those, just the time array. Especially in `_predict_volcanic_contributions` the fact that we passed data made me think that we need the smoothed temperature to predict the volcanic contributions but we actually don't. So I rewrote these two routines to just take `time` and `historic_period` as arguments. I understand a bit why it was not like this before because the code might have been a bit prettier before but I think it does make more sense now.
> Remove `data` from aod routines, just pass time directly

- CHANGELOG.rst
- ci/min_deps_check.py
- ci/requirements/min-all-deps.yml
- docs/source/installation.rst
- environment.yml
- mesmer/core/_datatreecompat.py
- mesmer/core/anomaly.py
- mesmer/core/datatree.py
- mesmer/core/volc.py
- mesmer/core/weighted.py
- mesmer/stats/_auto_regression.py
- mesmer/stats/_linear_regression.py
- setup.cfg
- tests/integration/test_calibrate_mesmer_newcodepath.py
- tests/integration/test_draw_realisations_mesmer_newcodepath.py
- tests/integration/test_draw_realisations_mesmer_x.py
- tests/unit/test_anomaly.py
- tests/unit/test_auto_regression.py
- tests/unit/test_auto_regression_scen_ens.py
- tests/unit/test_datatree.py
- tests/unit/test_linear_regression.py
- tests/unit/test_weighted.py
Drop support for `xarray-datatree` and require `xarray >= 2025.02`. WIP for now. I just saw something I want to address first in a separate PR.
> drop support for xarray-datatree

- mesmer/core/anomaly.py
- tests/unit/test_anomaly.py
Seen while working on #572, also uses `xr.testing.assert_equal` for `xr.DataTree` objects - forgotten in #627
> calc_anomaly: keep attrs

- mesmer/stats/_harmonic_model.py
- tests/unit/test_harmonic_model.py
Working on #572 I realized that I was too zealous in #624 - and we should allow more than 1 extra dimension (i.e. gridpoint and member, but let's generalize and allow any number).
> fit_harmonic_model: allow more dims

- CHANGELOG.rst
- mesmer/core/datatree.py
- mesmer/core/grid.py
- mesmer/core/mask.py
- mesmer/core/weighted.py
- mesmer/stats/_smoothing.py
- mesmer/testing.py
- tests/conftest.py
- tests/integration/test_calibrate_mesmer_newcodepath.py
- tests/integration/test_draw_realisations_mesmer_newcodepath.py
- tests/unit/test_grid.py
- tests/unit/test_grid_wrap.py
- tests/unit/test_mask.py
- tests/unit/test_smoothing.py
- tests/unit/test_weighted.py
Make many functions work with `xr.DataTree`. This will make #521 and #572 a bit simpler. Pretty cool because it's quite trivial. I still need to go over the statistical functions. Unfortunately this does not work for the auto regression functions because the `DataTree` argument (`seed`) is passed as a keyword-only - should we re-order them?
Oh yes, will be annoying to write the tests because it's so many functions. Will probably do minimal test only. The typing will come later (see #639).
https://github.com/MESMER-group/mesmer/blob/19a03beba5d3a45895834f943b9c2d58cfd498dd/mesmer/stats/_auto_regression.py#L377
> enable functions for xr.DataTree

- mesmer/core/datatree.py
- mesmer/core/grid.py
- mesmer/core/mask.py
- mesmer/core/regionmaskcompat.py
- mesmer/core/types.py
- mesmer/core/utils.py
- mesmer/core/volc.py
- mesmer/core/weighted.py
- mesmer/stats/_auto_regression.py
- mesmer/stats/_linear_regression.py
- mesmer/stats/_power_transformer.py
- mesmer/testing.py
- pyproject.toml
- tests/integration/test_calibrate_mesmer_newcodepath.py
- tests/integration/test_draw_realisations_mesmer_newcodepath.py
- tests/unit/test_auto_regression.py
- tests/unit/test_auto_regression_scen_ens.py
- tests/unit/test_computation.py
- tests/unit/test_harmonic_model.py
- tests/unit/test_smoothing.py
- tests/unit/test_weighted.py
Fix typing such that `mypy .` passes. This does not make pyright/ pylance happy _at all_ (it makes it a bit worse `pyright .` goes from 207 errors to 224. Not that mypy passes everything - it only checks the functions that are typed (e.g. functions that do not have type annotations are not checked). In contrast pyright seem to check everything. I tried to fix some of the pyright errors but I only added more problems... (and 200 are somehow too much to sanely handle, I already spent too much time with this...). In addition I realized that my approach in #639 is wrong - I 'll comment there.
> fix typing for mypy

- CHANGELOG.rst
- mesmer/core/volc.py
- tests/integration/test_calibrate_mesmer_newcodepath.py
- tests/integration/test_volc.py
Make `hist_period` optional in `fit_volcanic_influence` and `superimpose_volcanic_influence`. I decided that this closes #648 (even though the argument is not entirely removed but I am not sure it's possible to do so.)
> volc: make `hist_period` optional

- mesmer/core/volc.py
I forgot the to add the `f` for the f-string so the error message is not properly displayed. This is why you should test the full error message :man_shrugging:
> volc: fix error message

- CHANGELOG.rst
- mesmer/core/regionmaskcompat.py
- tests/unit/test_regionmaskcompat.py
Actually I realized that we can remove the _regionmaskcompat.py_ file because we could now require regionmask v0.12. 
```
Package           Required             Policy               Status
----------------- -------------------- -------------------- ------
regionmask        0.11    (2023-09-22) 0.12    (2024-03-21) <
```
> remove remove deprecated mask_percentage

- .readthedocs.yml
- docs/source/api_legacy.rst
In #658 I forgot to remove the functions from the API docs - this went unnoticed as sphinx does not error on on warnings.
> RTD: sphinx fail on warning

- docs/source/authors.rst
- docs/source/conf.py
- docs/source/index.rst
- docs/source/license.rst
- pyproject.toml
Adding _myst-parser_ as a dependency is overkill for adding the _AUTHORS_, however, this will also be used for #661 and potentially #521 (well this would require _myst\_nb_ but that depends on _myst-parser_).
> add authors and license to docs

- tests/integration/test_calibrate_mesmer_m.py
- tests/integration/test_calibrate_mesmer_newcodepath.py
- tests/integration/test_draw_mesmer_m.py
- tests/integration/test_draw_realisations_mesmer_newcodepath.py
`pytest.fixture` is not applied if there is a default value (cc @veni-vidi-vici-dormivi - I also just learned this)
```python
import pytest
@pytest.fixture
def param():
return True
def test_1(param):  # works
assert param
def test_2(param=False):  # fails
assert param
```
> fix pytest fixture usage

- tests/unit/test_weighted.py
Forgot to remove the `pytest.skip`
> re-enable weighted test for DataTree

- examples/example_mesmer_m.ipynb
- mesmer/io/_load_cmipng.py
- tests/integration/test_calibrate_mesmer_m.py
- tests/integration/test_calibrate_mesmer_newcodepath.py
- tests/integration/test_calibrate_mesmer_x.py
- tests/integration/test_draw_mesmer_m.py
- tests/integration/test_draw_realisations_mesmer_newcodepath.py
- tests/integration/test_draw_realisations_mesmer_x.py
- tests/unit/test_harmonic_model.py
- tests/unit/test_power_transformer.py
Not sure how big of a fan I am of these changes in xarray...
```diff
- data = xr.open_dataset(path, use_cftime=True)
+ time_coder = xr.coders.CFDatetimeCoder(use_cftime=True)
+ data = xr.open_dataset(path, decode_times=time_coder)
```
> fix xarray cftime deprecations warnings

- mesmer/core/utils.py
- tests/unit/test_utils.py
Extract the `_assert_required_dims` part from `_check_dataarray_form`. This is can also be relevant for `Dataset`.
1. Maybe we should actually check the `coords` and not the `dims`, as there can be `dims` without `coords` (but I don't know if _non-dimension-coords_ are a problem, so I don't have the nerve to go into this right now).
1. `_check_dataarray_form` should maybe also be renamed to `_assert_dataarray_form`.
2. (`__tracebackhide__` is a pytest thingy)
> extract `_assert_required_dims` from `_check_dataarray_form`

- CHANGELOG.rst
- mesmer/core/utils.py
- tests/unit/test_utils.py
Enable `Dataset` and` `DataTree` in `upsample_yearly_data`. Maybe it would be better to enable it for the stacked data, because that is potentially more transparent what we do with respect to #678 (stack monthly data and then pass it...). Well let's start here and maybe do this later?
> enable DataTree for `upsample_yearly_data`

- mesmer/core/utils.py
- tests/unit/test_utils.py
When stacking scenarios we get `"time"`, `"scenario"`, and `"member"` as non-dimension coordinates, which are not in `obj.dims`, so `"time" in obj.dims` is `False` and thus `required_dims` can error.
As hinted-at in #681
> add `_assert_required_coords`

- CHANGELOG.rst
- mesmer/core/utils.py
- tests/unit/test_utils.py
Allow non-dimension time coord in `upsample_yearly_data` - so we can pass pooled data in #572 (where `"scenario"` is the dim and `"time"` is a non-dimension coordinate). These 4 lines of code took me almost a day :man_shrugging: :shaking_face: (discovered a new emoji)
> allow non-dimension time coord in `upsample_yearly_data`

- mesmer/stats/_power_transformer.py
- tests/unit/test_power_transformer.py
As part of #572 we have to allow `sample_dim` in the power transformer. Previously `lambdas` would be an array with `month x year x others`. Now its `time x others`.
I implemented this in `get_lambdas_from_covariates` - but now there are two more params to pass to this function, which I don't particularly like (also it's not guaranteed that `yearly_pred` and `time_coords` both use the sample dim). However, users don't usually need to interact with `get_lambdas_from_covariates` (it's called in the `transform` and `inverse_transform` function).
Alternatively we could do it in `transform` and `inverse_transform`: 
```python
lambdas_stacked = (
lambdas.stack(__new__=(sample_dim, "month"), create_index=False)
.drop_vars(["month", time_dim], errors="ignore")
.swap_dims(__new__=sample_dim) …
```
> power transformer: allow sample dimension

- mesmer/core/_data.py
To be merged before #677 to avoid re-creating the data files twice. (Will lead to failed tests).
> aerosol_optical_depth: no longer round data

- tests/integration/test_draw_mesmer_m.py
- tests/integration/test_draw_realisations_mesmer_newcodepath.py
Create less emulations in the tests - so we need to store less data files. It's important that we test `n > 1` but I don't think it matters much whether it's `2` or more. As #697 to be merged before #677 to avoid re-creating the data files twice. (Will lead to failed tests).
> generate less test realisations

- mesmer/stats/_auto_regression.py
- tests/unit/test_auto_regression.py
Turns out the time dim was not ordered (even before), however, the order does not matter for the next step in the chain (estimating the covariance matrix). Also directly uses a linear regression.
> fit_auto_regression_monthly: keep order of sample dim

- .github/workflows/ci-workflow.yml
- CHANGELOG.rst
- docs/source/api.rst
- mesmer/__init__.py
- mesmer/core/options.py
- mesmer/core/utils.py
- mesmer/stats/_auto_regression.py
- mesmer/stats/_localized_covariance.py
- tests/unit/test_options.py
My tests in #712 were a bit underwhelming, however, I think this is still worth it.
- Large calibrations are likely run on linux systems & I saw good gains on our systems
- I get considerable gains on my old laptop
- There seems to be no speed loss on Mac/ Windows
I think it's more likely to run several jobs in parallel on large systems, so I made an upper limit. The `16` were semi-randomly chosen (`2 ** 4`), happy to adjust to something else.
I think there are currently only two places where we do a matrix decomposition.
I added `options`, a bit overkill for one option :man_shrugging:. I copied it from regionmask (originally adjusted from xarray).
> restrict threads and make them selectable

- mesmer/core/datatree.py
- tests/integration/test_calibrate_mesmer_newcodepath.py
- tests/unit/test_datatree.py
1. In #572 I use `_stack_datatree` in the example so this should be made public.
2. we have `mask_and_stack`, so I ended up with `tas_stacked_stacked_y` :grimacing: so my suggestion is to rename it to `pool`
(I am also not sure `datatree` is the best namespace but #348 :disappointed:)
@veni-vidi-vici-dormivi do you have thoughts on this?
> rename stack -> pool

- mesmer/calibrate_mesmer/train_lv.py
- mesmer/core/_data.py
- mesmer/core/datatree.py
- mesmer/core/geospatial.py
- mesmer/mesmer_x/_expression.py
- mesmer/mesmer_x/_probability_integral_transform.py
- mesmer/stats/_auto_regression.py
- mesmer/stats/_localized_covariance.py
- mesmer/testing.py
- tests/integration/test_calibrate_mesmer_m.py
- tests/integration/test_calibrate_mesmer_newcodepath.py
- tests/unit/test_auto_regression.py
- tutorials/tutorial_mesmer_calibrate_multiple_scenarios.ipynb
Went over all public functions in _stats_, _mesmer_x_, and _core_. It's not entirely consistent if `dim` is kw only or not.
> make more args kw only

- tests/integration/test_calibrate_mesmer_m.py
> MESMER-M calibration test: load using DataTree

- mesmer/_core/_data.py
- mesmer/io/load_obs.py
- mesmer/volc.py
- tests/integration/test_volc.py
- tests/unit/test_data.py
As per lengthy title. The function is only used internally, so not much point in exposing the  _data_ module. And it can just as well live in _volc_.
> move  `load_stratospheric_aerosol_optical_depth_obs` to volc and make data module private

- CHANGELOG.rst
- mesmer/distrib/_expression.py
- mesmer/distrib/_optimizers.py
- tests/unit/test_mesmer_x_expression.py
Removes `Expression.evaluate` in favor of `Expression.evaluate_params` and rewrites the last instance where it was used. Does make the computation of `crps` ever so slightly faster.
> Expression: remove evaluate

- mesmer/_core/utils.py
- tests/unit/test_utils.py
One CMIP6-ng model has this (KIOST-ESM). Is there a reason we don't have this atm @mathause?
> Add 365D to allowed freq for _assert_annual_data

- tests/unit/test_utils.py
> time freq: skip 'A' in pandas v3.0.0
